name 'iis_apps'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures iis_apps'
long_description 'Installs/Configures iis_apps'
version '0.1.0'

depends 'iis'
depends 'windows_firewall'
depends 'windows'
depends 'aws'